@url = http://localhost:3000

GET {{url}} HTTP/1.1

###

POST {{url}}/pessoa HTTP/1.1
Content-Type: application/json

{
    "nome": "Fulano",
    "sobrenome": "Ciclano"
}

###

GET {{url}}/pessoa HTTP/1.1

###

GET {{url}}/pessoa/6 HTTP/1.1

###

PUT {{url}}/pessoa/1 HTTP/1.1
Content-Type: application/json

{
    "nome": "Brian",
    "sobrenome": "Morais"
}

###

DELETE {{url}}/pessoa/5 HTTP/1.1